import {handleVercelRequest} from '../../../server/vercel.mjs';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export const maxDuration=60;
export const GET=handleVercelRequest;
export const POST=handleVercelRequest;
export const PATCH=handleVercelRequest;
export const PUT=handleVercelRequest;
export const DELETE=handleVercelRequest;
export const OPTIONS=handleVercelRequest;
export const HEAD=handleVercelRequest;
