// External providers are optional. Secrets stay on the server; no delivery is simulated.
const enc=new TextEncoder();
const q=(env,sql,...a)=>env.DB.prepare(sql).bind(...a);
const one=(env,sql,...a)=>q(env,sql,...a).first();
const all=async(env,sql,...a)=>(await q(env,sql,...a).all()).results;
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const now=()=>new Date().toISOString();
export const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))),x=>x.toString(16).padStart(2,'0')).join('');
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
export const emailReady=env=>!!(env.RESEND_API_KEY&&env.EMAIL_FROM);
export const googleReady=env=>!!(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET&&env.GOOGLE_REDIRECT_URI);
export const billingReady=env=>!!(env.DODO_PAYMENTS_API_KEY&&env.DODO_STARTER_PRODUCT_ID&&env.DODO_AGENCY_PRODUCT_ID&&env.DODO_STUDIO_PRODUCT_ID);
export const serviceStatus=env=>({google:googleReady(env),email:emailReady(env),billing:billingReady(env)});
function appOrigin(req,env){const origin=env.APP_ORIGIN||new URL(req.url).origin;const u=new URL(origin);if(u.protocol!=='https:'&&u.hostname!=='localhost'&&u.hostname!=='127.0.0.1')fail('The application URL must use HTTPS.',503);return u.origin;}
export async function sendMail(env,to,subject,text,id){if(!emailReady(env))fail('Email delivery is not connected yet. Ask the site owner to complete email setup.',503);const res=await (env.MAIL_FETCH||fetch)('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':id||crypto.randomUUID()},body:JSON.stringify({from:env.EMAIL_FROM,to:[to],subject,text}),signal:AbortSignal.timeout(10000)});if(!res.ok)fail('The email provider could not accept this message. Please try again later.',502);return (await res.json()).id;}
export async function requestAccountEmail(req,env,user,purpose,email){if(!emailReady(env))fail('Email delivery is not connected yet. Ask the site owner to complete email setup.',503);const u=purpose==='verify'?user:await one(env,'SELECT id,email,name FROM users WHERE email=?',String(email||'').trim().toLowerCase());if(!u)return {ok:true,message:'If an account exists, a reset link has been sent.'};if(purpose==='verify'&&user.email_verified)return {ok:true,message:'Your email is already verified.'};const raw=token(),id=await digest(raw);await q(env,'INSERT INTO auth_tokens(token,user_id,purpose,expires,used,created_at) VALUES(?,?,?,?,0,?)',id,u.id,purpose,Date.now()+(purpose==='reset'?1800000:86400000),now()).run();try{const action=purpose==='reset'?'reset-password':'verify-email';await sendMail(env,u.email,purpose==='reset'?'Reset your Redlyn password':'Verify your Redlyn email',`Hi ${u.name},\n\n${purpose==='reset'?'Reset your password':'Verify your email'} using this link:\n${appOrigin(req,env)}/${action}#${raw}\n\nThis link expires ${purpose==='reset'?'in 30 minutes':'in 24 hours'} and can be used once. If you did not request it, ignore this email.`,id);}catch(e){await q(env,'DELETE FROM auth_tokens WHERE token=?',id).run();throw e;}return {ok:true,message:purpose==='reset'?'If an account exists, a reset link has been sent.':'Verification email sent.'};}
export async function useAccountToken(env,raw,purpose,passwordHash,password){const id=await digest(String(raw||'')),t=await one(env,'SELECT * FROM auth_tokens WHERE token=? AND purpose=? AND used=0 AND expires>?',id,purpose,Date.now());if(!t)fail('This link is invalid or expired. Request a new one.');if(purpose==='reset'&&(typeof password!=='string'||password.length<10||password.length>200))fail('Choose a password of 10–200 characters.');const update=purpose==='reset'?q(env,'UPDATE users SET password=? WHERE id=? AND EXISTS(SELECT 1 FROM auth_tokens WHERE token=? AND used=0 AND expires>?)',await passwordHash(password),t.user_id,id,Date.now()):q(env,'UPDATE users SET email_verified=1 WHERE id=? AND EXISTS(SELECT 1 FROM auth_tokens WHERE token=? AND used=0 AND expires>?)',t.user_id,id,Date.now());const jobs=[update];if(purpose==='reset')jobs.push(q(env,'DELETE FROM sessions WHERE user_id=? AND EXISTS(SELECT 1 FROM auth_tokens WHERE token=? AND used=0)',t.user_id,id));jobs.push(q(env,'UPDATE auth_tokens SET used=1 WHERE user_id=? AND purpose=? AND used=0',t.user_id,purpose));const result=await env.DB.batch(jobs);if(!(result[0].meta?.changes??result[0].changes))fail('This link has already been used.');return {ok:true};}
export async function notifyMentions(req,env,project,author,text,internal,feedbackId){const users=await all(env,'SELECT id,name,email,email_verified FROM users WHERE id=? OR id IN (SELECT user_id FROM workspace_members WHERE owner_id=?) OR id IN (SELECT user_id FROM members WHERE project_id=?)',project.owner_id,project.owner_id,project.id);const names=String(text).toLowerCase();for(const u of users){if(u.name===author||!names.includes('@'+u.name.toLowerCase())||!new RegExp('@'+u.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=$|[\\s.,!?;:])','i').test(text))continue;const id=crypto.randomUUID();await q(env,'INSERT INTO notifications(id,user_id,project_id,feedback_id,author,text,internal,read,created_at,email_state) VALUES(?,?,?,?,?,?,?,0,?,?)',id,u.id,project.id,feedbackId,author,String(text).slice(0,4000),internal?1:0,now(),emailReady(env)&&u.email_verified?'pending':'disabled').run();if(emailReady(env)&&u.email_verified){try{await sendMail(env,u.email,author+' mentioned you in '+project.name,`${author} mentioned you in ${project.name}.\n\nOpen your workspace to read the ${internal?'internal ':''}comment:\n${appOrigin(req,env)}/t/${project.id}\n\nComment contents are kept in your workspace.`,id);await q(env,"UPDATE notifications SET email_state='sent' WHERE id=?",id).run();}catch{await q(env,"UPDATE notifications SET email_state='failed' WHERE id=?",id).run();}}}}
export const PLANS={Free:{websites:1,members:1,views:300},Starter:{websites:5,members:2,views:300},Agency:{websites:20,members:5,views:300},Studio:{websites:null,members:null,views:300}};
export async function entitlement(env,owner){const row=await one(env,'SELECT * FROM subscriptions WHERE owner_id=?',owner);const stale=!!(row&&billingReady(env)&&row.updated_at<Date.now()-3600000);const active=row&&row.status==='active'&&row.valid_until>Date.now()&&!stale;const plan=active&&PLANS[row.plan]?row.plan:'Free';const configured=Number(env[plan.toUpperCase()+'_DAILY_VIEWS']);const limits={...PLANS[plan],views:Number.isSafeInteger(configured)&&configured>0?configured:PLANS[plan].views};const testMembers=Number(env.TEST_TEAM_MEMBER_LIMIT),testUntil=Date.parse(env.TEST_TEAM_UNTIL||'');const testing=plan==='Free'&&Number.isSafeInteger(testMembers)&&testMembers>=2&&testMembers<=10&&testUntil>Date.now()?{members:testMembers,expires:testUntil}:null;if(testing)limits.members=testing.members;return {plan,limits,subscription:row||null,billingStale:stale,testing};}
export const membershipSQL='SELECT user_id FROM workspace_members WHERE owner_id=? UNION SELECT m.user_id FROM members m JOIN projects p ON p.id=m.project_id WHERE p.owner_id=? AND m.user_id<>p.owner_id';
export async function memberCount(env,owner){return 1+(await one(env,'SELECT COUNT(*) AS n FROM ('+membershipSQL+')',owner,owner)).n;}
export async function enforceLimit(env,owner,kind){const e=await entitlement(env,owner),limit=e.limits[kind];if(limit===null)return;let count;if(kind==='websites')count=(await one(env,'SELECT COUNT(*) AS n FROM projects WHERE owner_id=? AND archived=0',owner)).n;else if(kind==='members')count=await memberCount(env,owner);else return;if(count>=limit)fail(`${e.plan} includes ${limit} ${kind}. ${kind==='websites'?'Archive a review or upgrade your plan.':'Remove a teammate or upgrade your plan.'}`,409);}
async function provider(env,path,method='GET',body){if(!env.DODO_PAYMENTS_API_KEY)fail('Payments are not connected yet. Ask the site owner to complete billing setup.',503);const base=env.DODO_ENVIRONMENT==='live'?'https://live.dodopayments.com':'https://test.dodopayments.com';const r=await(env.BILLING_FETCH||fetch)(base+path,{method,headers:{Authorization:'Bearer '+env.DODO_PAYMENTS_API_KEY,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)});if(!r.ok)fail('The payment service could not complete the request. Please try again.',502);return r.status===204?{}:r.json();}
const productPlan=(env,product)=>['Starter','Agency','Studio'].find(p=>env['DODO_'+p.toUpperCase()+'_PRODUCT_ID']===product);
export async function storeSubscription(env,sub,owner,timestamp=Date.now()){const plan=productPlan(env,sub.product_id);if(!plan||!sub.subscription_id||!owner)return false;const existing=await one(env,'SELECT * FROM subscriptions WHERE owner_id=?',owner);if(existing&&existing.updated_at>timestamp)return false;if(existing&&existing.subscription_id!==sub.subscription_id&&existing.status==='active'&&existing.valid_until>Date.now())fail('This workspace already has an active subscription.',409);const until=sub.next_billing_date?Date.parse(sub.next_billing_date):null;if(sub.status==='active'&&(!Number.isFinite(until)||until<=Date.now()))fail('The payment service returned an invalid subscription period.',502);await q(env,'INSERT INTO subscriptions(owner_id,subscription_id,customer_id,product_id,plan,status,valid_until,cancel_at_end,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_id) DO UPDATE SET subscription_id=excluded.subscription_id,customer_id=excluded.customer_id,product_id=excluded.product_id,plan=excluded.plan,status=excluded.status,valid_until=excluded.valid_until,cancel_at_end=excluded.cancel_at_end,updated_at=excluded.updated_at',owner,sub.subscription_id,sub.customer?.customer_id||'',sub.product_id,plan,sub.status,Number.isFinite(until)?until:null,sub.cancel_at_next_billing_date?1:0,timestamp).run();return true;}
export async function checkout(req,env,user,owner,plan){if(!billingReady(env))fail('Payments are not connected yet. Ask the site owner to complete billing setup.',503);if(!['Starter','Agency','Studio'].includes(plan))fail('Choose a paid plan.');const current=await entitlement(env,owner);if(current.plan!=='Free'||current.subscription&&['active','on_hold','pending'].includes(current.subscription.status))fail('Manage your existing subscription before starting another.',409);const requestId=crypto.randomUUID();const inserted=await q(env,'INSERT INTO billing_checkouts(id,owner_id,session_id,plan,created_at) SELECT ?,?,NULL,?,? WHERE NOT EXISTS(SELECT 1 FROM billing_checkouts WHERE owner_id=? AND created_at>?)',requestId,owner,plan,Date.now(),owner,Date.now()-600000).run();if(!(inserted.meta?.changes??inserted.changes))fail('A checkout was started recently. Complete it or wait ten minutes before retrying.',409);const origin=appOrigin(req,env);let r;try{r=await provider(env,'/checkouts','POST',{product_cart:[{product_id:env['DODO_'+plan.toUpperCase()+'_PRODUCT_ID'],quantity:1}],customer:{email:user.email,name:user.name},metadata:{workspace_id:owner,checkout_request_id:requestId},return_url:origin+'/app/usage?checkout=return',cancel_url:origin+'/app/usage',feature_flags:{allow_customer_editing_email:false},customization:{theme:'dark'}});}catch(e){await q(env,'DELETE FROM billing_checkouts WHERE id=?',requestId).run();throw e;}if(!r.session_id||!r.checkout_url||!/^https:\/\/[a-z0-9.-]+\.dodopayments\.com\//i.test(r.checkout_url))fail('The payment service returned an invalid checkout.',502);await q(env,'UPDATE billing_checkouts SET session_id=? WHERE id=?',r.session_id,requestId).run();return {url:r.checkout_url};}
export async function syncBilling(env,owner){const existing=(await entitlement(env,owner)).subscription;if(existing?.subscription_id){if(existing.updated_at>Date.now()-60000)return entitlement(env,owner);const sub=await provider(env,'/subscriptions/'+encodeURIComponent(existing.subscription_id));await storeSubscription(env,sub,owner);return entitlement(env,owner);}const pending=await all(env,'SELECT * FROM billing_checkouts WHERE owner_id=? AND session_id IS NOT NULL AND created_at>? ORDER BY created_at DESC LIMIT 3',owner,Date.now()-86400000);for(const c of pending){const session=await provider(env,'/checkouts/'+encodeURIComponent(c.session_id));if(session.payment_status!=='succeeded'||!session.payment_id)continue;const payment=await provider(env,'/payments/'+encodeURIComponent(session.payment_id));if(!payment.subscription_id)continue;const sub=await provider(env,'/subscriptions/'+encodeURIComponent(payment.subscription_id));if(sub.metadata?.checkout_request_id!==c.id||sub.metadata?.workspace_id!==owner||sub.product_id!==env['DODO_'+c.plan.toUpperCase()+'_PRODUCT_ID'])fail('The payment could not be matched to this workspace.',403);await storeSubscription(env,sub,owner);break;}return entitlement(env,owner);}
export async function cancelBilling(env,owner){const e=await entitlement(env,owner);if(!e.subscription?.subscription_id)fail('No subscription to cancel.');const sub=await provider(env,'/subscriptions/'+encodeURIComponent(e.subscription.subscription_id),'PATCH',{cancel_at_next_billing_date:true});await storeSubscription(env,sub,owner);return entitlement(env,owner);}
export async function billingWebhook(req,env){if(!env.DODO_PAYMENTS_WEBHOOK_KEY)fail('Webhook is not configured.',503);const body=await req.text();if(body.length>262144)fail('Webhook too large.',413);const id=req.headers.get('webhook-id'),stamp=req.headers.get('webhook-timestamp'),signatures=req.headers.get('webhook-signature')||'';if(!id||!stamp||!/^[0-9]+$/.test(stamp)||Math.abs(Date.now()/1000-Number(stamp))>300)fail('Invalid webhook signature.',401);let bytes;try{bytes=Uint8Array.from(atob(env.DODO_PAYMENTS_WEBHOOK_KEY.replace(/^whsec_/,'')),c=>c.charCodeAt(0));}catch{fail('Webhook configuration invalid.',503);}const key=await crypto.subtle.importKey('raw',bytes,{name:'HMAC',hash:'SHA-256'},false,['verify']);let valid=false;for(const part of signatures.split(' ')){const [version,sig]=part.split(',');if(version!=='v1'||!sig)continue;try{if(await crypto.subtle.verify('HMAC',key,Uint8Array.from(atob(sig),c=>c.charCodeAt(0)),enc.encode(id+'.'+stamp+'.'+body)))valid=true;}catch{}}if(!valid)fail('Invalid webhook signature.',401);if(await one(env,'SELECT id FROM billing_events WHERE id=?',id))return {ok:true,duplicate:true};let event;try{event=JSON.parse(body);}catch{fail('Invalid webhook payload.');}if(String(event.type).startsWith('subscription.')){const sub=event.data,owner=sub?.metadata?.workspace_id,request=sub?.metadata?.checkout_request_id;const mapping=owner&&request?await one(env,'SELECT * FROM billing_checkouts WHERE id=? AND owner_id=?',request,owner):null;const existing=sub?.subscription_id?await one(env,'SELECT owner_id FROM subscriptions WHERE subscription_id=?',sub.subscription_id):null;const matched=existing?.owner_id||mapping?.owner_id;if(matched&&(existing||!mapping||sub.product_id===env['DODO_'+mapping.plan.toUpperCase()+'_PRODUCT_ID'])){const ts=Date.parse(event.timestamp);if(!Number.isFinite(ts))fail('Invalid event timestamp.');await storeSubscription(env,sub,matched,ts);}}await q(env,'INSERT OR IGNORE INTO billing_events(id,created_at) VALUES(?,?)',id,Date.now()).run();return {ok:true};}

export async function invitationEmail(req,env,email,token,path,name){if(!emailReady(env))return {emailSent:false,emailError:'Email delivery is not connected. Share the invitation link.'};try{await sendMail(env,email,'You are invited to '+name,`You have been invited to ${name}.\n\nSign in with ${email} to accept within 7 days:\n${appOrigin(req,env)}/${path}/${token}`,await digest(token));return {emailSent:true};}catch{return {emailSent:false,emailError:'The invitation was created, but email delivery failed. Share the invitation link.'};}}
