import {memberCount,serviceStatus,requestAccountEmail,useAccountToken,notifyMentions,entitlement,enforceLimit,checkout,syncBilling,cancelBilling,billingWebhook,invitationEmail} from './integrations.mjs';
import {previewDocument,previewError,captureAsset} from './preview.mjs';
const enc = new TextEncoder();
const now = () => new Date().toISOString();
const uid = () => crypto.randomUUID();
const secret = () => Array.from(crypto.getRandomValues(new Uint8Array(32)), x => x.toString(16).padStart(2,'0')).join('');
const hash = async s => Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
const json = (data,status=200,headers={}) => new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
const fail = (message,status=400) => {throw Object.assign(new Error(message),{status});};
export async function passwordHash(password,salt=secret()) {
 const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);
 const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256);
 return salt+':'+Array.from(new Uint8Array(bits),x=>x.toString(16).padStart(2,'0')).join('');
}
async function passwordOK(p,stored){return stored && await passwordHash(p,stored.split(':')[0])===stored;}
const text = (v,max=4000) => typeof v==='string' ? v.trim().slice(0,max) : '';
export function validUrl(value){try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)fail('Enter a public http or https website URL.'); return u.href;}catch{fail('Enter a valid website URL.');}}
const q=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const one=(env,sql,...args)=>q(env,sql,...args).first();
const all=async(env,sql,...args)=>(await q(env,sql,...args).all()).results;
async function body(req){try{return await req.json();}catch{fail('Invalid request.');}}
async function auth(req,env,required=true){const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)redlyn_session=([^;]+)/)?.[1];const u=raw?await one(env,'SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires>?',await hash(raw),Date.now()):null;if(!u&&required)fail('Please log in to continue.',401);return u;}
async function member(req,env,id){const u=await auth(req,env);const p=await one(env,'SELECT * FROM projects WHERE id=?',id);if(!p)fail('Project not found.',404);const m=await one(env,'SELECT role FROM workspace_members WHERE owner_id=? AND user_id=?',p.owner_id,u.id)||await one(env,'SELECT role FROM members WHERE project_id=? AND user_id=?',id,u.id);if(p.owner_id!==u.id&&!m)fail('You do not have access to this project.',403);return {project:p,user:u,role:p.owner_id===u.id?'owner':m.role,team:true,name:u.name};}
async function context(req,env,id){const st=req.headers.get('X-Review-Session');if(st){const r=await one(env,'SELECT reviewers.*, links.project_id, links.revoked, links.expires, links.can_comment, links.can_approve FROM reviewers JOIN links ON links.id=reviewers.link_id WHERE reviewers.token=?',await hash(st));if(!r||r.project_id!==id||r.revoked||r.expires&&r.expires<Date.now())fail('This review link has expired or been revoked.',403);const p=await one(env,'SELECT * FROM projects WHERE id=? AND archived=0',id);if(!p)fail('This project is unavailable.',404);return {project:p,team:false,name:r.name,reviewer:r};}return member(req,env,id);}
function admin(c){if(!['owner','admin'].includes(c.role))fail('Only the project owner or an admin can make this change.',403);}
async function event(env,p,author,message,internal=0){await q(env,'INSERT INTO activity VALUES(?,?,?,?,?,?)',uid(),p,author,message,internal,now()).run();}
async function link(env,token){const l=await one(env,'SELECT * FROM links WHERE token_hash=?',await hash(token));if(!l||l.revoked||l.expires&&l.expires<Date.now())fail('This review link has expired or been revoked.',404);const p=await one(env,'SELECT * FROM projects WHERE id=? AND archived=0',l.project_id);if(!p)fail('This project is unavailable.',404);return {l,p};}
async function makeLink(env,p,b){const token=secret(),id=uid();await q(env,'INSERT INTO links(id,project_id,token_hash,label,expires,require_email,password,can_comment,can_approve,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',id,p,await hash(token),text(b.label,80)||'Client link',b.expires?new Date(b.expires).getTime():null,b.require_email?1:0,b.password?await passwordHash(text(b.password,200)):null,b.can_comment===false?0:1,b.can_approve===false?0:1,now()).run();return {id,token};}
async function rateLimit(req,env,kind,max=30){const ip=req.headers.get('CF-Connecting-IP')||'local';const key=await hash(ip+kind);const existing=await one(env,'SELECT count, reset_at FROM rate_limits WHERE id=?',key);if(existing&&existing.reset_at>Date.now()&&existing.count>=max)fail('Too many attempts. Please try again in a few minutes.',429);await q(env,'INSERT INTO rate_limits(id,count,reset_at) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN reset_at<? THEN 1 ELSE count+1 END, reset_at=CASE WHEN reset_at<? THEN ? ELSE reset_at END',key,Date.now()+300000,Date.now(),Date.now(),Date.now()+300000).run();}
async function api(req,env){if(new URL(req.url).pathname==='/api/billing/webhook'&&req.method==='POST')return json(await billingWebhook(req,env));const url=new URL(req.url),path=url.pathname,m=req.method,b=['POST','PATCH','PUT'].includes(m)&&!path.endsWith('/uploads')?await body(req):{};
 if(['POST','PATCH','PUT','DELETE'].includes(m)){const origin=req.headers.get('Origin');if(origin&&origin!==url.origin)fail('Request origin is not permitted.',403);}
 if(path==='/api/auth/google'&&m==='GET'){
  if(!env.GOOGLE_CLIENT_ID||!env.GOOGLE_CLIENT_SECRET||!env.GOOGLE_REDIRECT_URI)fail('Google sign-in is not configured. Use email and password.',503);
  const state=secret(),verifier=secret(),challenge=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(verifier))))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
  const location=new URL('https://accounts.google.com/o/oauth2/v2/auth');location.search=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:env.GOOGLE_REDIRECT_URI,response_type:'code',scope:'openid email profile',state,code_challenge:challenge,code_challenge_method:'S256'});
  return new Response(null,{status:302,headers:{Location:location.href,'Set-Cookie':`redlyn_oauth=${state}:${verifier}:${Date.now()}; HttpOnly; SameSite=Lax; Path=/api/auth/google; Max-Age=600${url.protocol==='https:'?'; Secure':''}`,'Cache-Control':'no-store'}});
 }
 if(path==='/api/auth/google/callback'&&m==='GET'){
  const cookie=req.headers.get('cookie')?.match(/(?:^|;\s*)redlyn_oauth=([^;]+)/)?.[1]?.split(':');
  if(!env.GOOGLE_CLIENT_SECRET||!cookie||cookie[0]!==url.searchParams.get('state')||Date.now()-Number(cookie[2])>600000||Number(cookie[2])>Date.now()||!url.searchParams.get('code'))fail('Google sign-in could not be verified. Please start again.',403);
  const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:env.GOOGLE_REDIRECT_URI,code:url.searchParams.get('code'),code_verifier:cookie[1],grant_type:'authorization_code'})});
  if(!response.ok)fail('Google sign-in failed. Please try again.',403);const tokens=await response.json();const profileResponse=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:'Bearer '+tokens.access_token}});if(!profileResponse.ok)fail('Unable to verify your Google profile.',403);const profile=await profileResponse.json();if(!profile.email_verified||!profile.sub||!profile.email)fail('A verified Google email is required.',403);
  let u=await one(env,'SELECT * FROM users WHERE google_id=?',profile.sub);if(!u){const email=text(profile.email,254).toLowerCase();if(await one(env,'SELECT id FROM users WHERE email=?',email))fail('This email already uses password sign-in. Log in with your existing password.',409);u={id:uid(),email,name:text(profile.name,80)||email};await q(env,'INSERT INTO users(id,email,name,password,created_at,google_id,email_verified) VALUES(?,?,?,?,?,?,1)',u.id,u.email,u.name,'google-only',now(),profile.sub).run();}
  await q(env,'UPDATE users SET email_verified=1 WHERE id=?',u.id).run();const session=await sessionResponse(env,u,url.protocol==='https:');const h=new Headers(session.headers);h.set('Location','/app');h.delete('Content-Type');h.append('Set-Cookie','redlyn_oauth=; HttpOnly; SameSite=Lax; Path=/api/auth/google; Max-Age=0');return new Response(null,{status:302,headers:h});
 }
 if(path==='/api/auth/signup'&&m==='POST'){
  await rateLimit(req,env,'signup');const email=text(b.email,254).toLowerCase(),name=text(b.name,80),password=b.password;
  if(!name||!/^\S+@\S+\.\S+$/.test(email)||typeof password!=='string'||password.length<10||password.length>200)fail('Enter your name, email and a password of 10–200 characters.');
  if(await one(env,'SELECT id FROM users WHERE email=?',email))fail('An account already exists for this email.');
  const id=uid();await q(env,'INSERT INTO users(id,email,name,password,created_at) VALUES(?,?,?,?,?)',id,email,name,await passwordHash(password),now()).run();
  return sessionResponse(env,{id,email,name},url.protocol==='https:');
 }
 if(path==='/api/auth/forgot-password'&&m==='POST'){await rateLimit(req,env,'reset-email');return json(await requestAccountEmail(req,env,null,'reset',b.email));}
 if(path==='/api/auth/verification-email'&&m==='POST'){const u=await auth(req,env);await rateLimit(req,env,'verify-email');return json(await requestAccountEmail(req,env,u,'verify'));}
 if(['/api/auth/reset-password','/api/auth/verify-email'].includes(path)&&m==='POST'){await rateLimit(req,env,'account-token');return json(await useAccountToken(env,b.token,path.endsWith('reset-password')?'reset':'verify',passwordHash,b.password));}
 if(path==='/api/auth/login'&&m==='POST'){await rateLimit(req,env,'login');const u=await one(env,'SELECT * FROM users WHERE email=?',text(b.email,254).toLowerCase());if(!u||!await passwordOK(b.password||'',u.password))fail('The email or password is incorrect.',401);return sessionResponse(env,u,url.protocol==='https:');}
 if(path==='/api/auth/logout'&&m==='POST'){const raw=req.headers.get('cookie')?.match(/redlyn_session=([^;]+)/)?.[1];if(raw)await q(env,'DELETE FROM sessions WHERE token=?',await hash(raw)).run();return json({ok:true},200,{'Set-Cookie':'redlyn_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
 if(path==='/api/me'){const u=await auth(req,env,false);if(m==='PATCH'){if(!u)fail('Please log in.',401);const name=text(b.name,80);if(!name)fail('Enter your name.');await q(env,'UPDATE users SET name=? WHERE id=?',name,u.id).run();return json({user:{id:u.id,email:u.email,name,emailVerified:!!u.email_verified}});}return json({user:u?{id:u.id,name:u.name,email:u.email,emailVerified:!!u.email_verified}:null,services:serviceStatus(env),googleEnabled:serviceStatus(env).google,billingEnabled:serviceStatus(env).billing});}
 if(['/api/billing','/api/billing/sync','/api/billing/cancel'].includes(path)&&m==='POST'){const u=await auth(req,env),owner=b.workspaceId||u.id;if(owner!==u.id)fail('Only the workspace owner can manage billing.',403);await rateLimit(req,env,'billing');return json(path==='/api/billing'?await checkout(req,env,u,owner,b.plan):path.endsWith('/sync')?await syncBilling(env,owner):await cancelBilling(env,owner));}
 if(path==='/api/notifications'&&m==='GET'){const u=await auth(req,env);return json({notifications:await all(env,'SELECT n.*,p.name AS project_name FROM notifications n JOIN projects p ON p.id=n.project_id JOIN feedback f ON f.id=n.feedback_id WHERE n.user_id=? AND (p.owner_id=? OR p.owner_id IN (SELECT owner_id FROM workspace_members WHERE user_id=?) OR p.id IN (SELECT project_id FROM members WHERE user_id=?)) AND (? IS NULL OR p.owner_id=?) ORDER BY n.created_at DESC LIMIT 100',u.id,u.id,u.id,u.id,url.searchParams.get('workspace'),url.searchParams.get('workspace'))});}
 if(path==='/api/notifications/read'&&m==='POST'){const u=await auth(req,env);await q(env,'UPDATE notifications SET read=1 WHERE user_id=? AND id=?',u.id,text(b.id,80)).run();return json({ok:true});}
 if(path==='/api/workspaces'&&m==='GET'){const u=await auth(req,env);const rows=await all(env,'SELECT u.id,u.name,ws.name AS workspace_name FROM users u LEFT JOIN workspace_settings ws ON ws.owner_id=u.id WHERE u.id=? OR u.id IN (SELECT owner_id FROM workspace_members WHERE user_id=?) OR u.id IN (SELECT p.owner_id FROM projects p JOIN members m ON m.project_id=p.id WHERE m.user_id=?)',u.id,u.id,u.id);return json({workspaces:await Promise.all(rows.map(async r=>({id:r.id,name:r.workspace_name||r.name+'’s workspace',owner:r.id===u.id,plan:(await entitlement(env,r.id)).plan})))});}
 const wm=path.match(/^\/api\/workspaces\/([^/]+)(?:\/(members|invitations)(?:\/([^/]+))?)?$/);
 if(wm){const u=await auth(req,env),owner=await one(env,'SELECT id,name FROM users WHERE id=?',wm[1]);if(!owner)fail('Workspace not found.',404);const member=await one(env,'SELECT role FROM workspace_members WHERE owner_id=? AND user_id=?',owner.id,u.id),role=owner.id===u.id?'owner':member?.role;if(!role)fail('You do not have access to this workspace.',403);const canManage=['owner','admin'].includes(role);if(!wm[2]){if(m==='GET'){const setting=await one(env,'SELECT name FROM workspace_settings WHERE owner_id=?',owner.id);return json({id:owner.id,name:setting?.name||owner.name+'’s workspace',role});}if(m==='PATCH'){if(!canManage)fail('Only workspace admins can change settings.',403);const name=text(b.name,100);if(!name)fail('Enter a workspace name.');await q(env,'INSERT INTO workspace_settings VALUES(?,?) ON CONFLICT(owner_id) DO UPDATE SET name=excluded.name',owner.id,name).run();return json({ok:true});}}
 if(wm[2]==='members'){if(m==='GET')return json({role,testing:(await entitlement(env,owner.id)).testing,members:await all(env,'SELECT u.id,u.name,u.email,m.role FROM workspace_members m JOIN users u ON u.id=m.user_id WHERE m.owner_id=? UNION SELECT id,name,email,\'owner\' FROM users WHERE id=?',owner.id,owner.id),invitations:canManage?await all(env,'SELECT id,email,role,expires FROM workspace_invitations WHERE owner_id=? AND accepted=0 AND expires>?',owner.id,Date.now()):[]});if(!canManage&&!(m==='DELETE'&&wm[3]===u.id))fail('Only workspace admins can manage members.',403);if(m==='POST'){const email=text(b.email,254).toLowerCase();if(email&&!/^\S+@\S+\.\S+$/.test(email))fail('Enter a valid email address.');const invited=await one(env,'SELECT id FROM users WHERE email=?',email);if(invited&&(invited.id===owner.id||await one(env,'SELECT role FROM workspace_members WHERE owner_id=? AND user_id=?',owner.id,invited.id)))fail('This person is already in the workspace.');await enforceLimit(env,owner.id,'members');const token=secret();await q(env,'INSERT INTO workspace_invitations VALUES(?,?,?,?,?,?,0)',uid(),owner.id,email,['admin','designer','developer'].includes(b.role)?b.role:'developer',await hash(token),Date.now()+604800000).run();return json({token,...(b.send_email&&email?await invitationEmail(req,env,email,token,'workspace-invite',owner.name+'’s workspace'):{})});}if(wm[3]){if(wm[3]===owner.id)fail('The workspace owner cannot be removed.',400);if(m==='DELETE'){await q(env,'DELETE FROM workspace_members WHERE owner_id=? AND user_id=?',owner.id,wm[3]).run();return json({ok:true});}if(m==='PATCH'){if(!['admin','designer','developer'].includes(b.role))fail('Invalid role.');await q(env,'UPDATE workspace_members SET role=? WHERE owner_id=? AND user_id=?',b.role,owner.id,wm[3]).run();return json({ok:true});}}}
 if(wm[2]==='invitations'&&wm[3]&&m==='DELETE'){if(!canManage)fail('Only workspace admins can revoke invitations.',403);await q(env,'UPDATE workspace_invitations SET expires=0 WHERE owner_id=? AND id=?',owner.id,wm[3]).run();return json({ok:true});}}
 const wi=path.match(/^\/api\/workspace-invite\/([^/]+)$/);if(wi){const invite=await one(env,`SELECT i.*,COALESCE(ws.name,u.name||'’s workspace') AS name FROM workspace_invitations i JOIN users u ON u.id=i.owner_id LEFT JOIN workspace_settings ws ON ws.owner_id=i.owner_id WHERE token_hash=?`,await hash(wi[1]));if(!invite||invite.accepted||invite.expires<Date.now())fail('This invitation is no longer available.',404);if(m==='GET')return json({name:invite.name,email:invite.email,role:invite.role});if(m!=='POST')fail('Method not allowed.',405);const u=await auth(req,env);if(invite.email&&u.email!==invite.email)fail('Sign in with the invited email address.',403);if(u.id===invite.owner_id)fail('You already own this workspace.');await enforceLimit(env,invite.owner_id,'members');const cap=(await entitlement(env,invite.owner_id)).limits.members;const accepted=await env.DB.batch([q(env,'INSERT OR REPLACE INTO workspace_members(owner_id,user_id,role) SELECT owner_id,?,role FROM workspace_invitations WHERE id=? AND accepted=0 AND expires>? AND (? IS NULL OR (SELECT COUNT(*) FROM (SELECT user_id FROM workspace_members WHERE owner_id=workspace_invitations.owner_id UNION SELECT m.user_id FROM members m JOIN projects p ON p.id=m.project_id WHERE p.owner_id=workspace_invitations.owner_id AND m.user_id<>p.owner_id))+1<?)',u.id,invite.id,Date.now(),cap,cap),q(env,'UPDATE workspace_invitations SET accepted=1 WHERE id=? AND accepted=0 AND EXISTS(SELECT 1 FROM workspace_members w WHERE w.owner_id=workspace_invitations.owner_id AND w.user_id=?)',invite.id,u.id)]);if(!(accepted[0].meta?.changes??accepted[0].changes))fail('This invitation is no longer available.',404);return json({workspaceId:invite.owner_id});}
 if(path==='/api/usage'&&m==='GET'){const u=await auth(req,env),owner=url.searchParams.get('workspace')||u.id;if(owner!==u.id&&!await one(env,'SELECT role FROM workspace_members WHERE owner_id=? AND user_id=?',owner,u.id))fail('You do not have access to workspace usage.',403);const day=now().slice(0,10),month=day.slice(0,7);const comments=await one(env,'SELECT COALESCE(SUM(CASE WHEN substr(f.created_at,1,10)=? THEN 1 ELSE 0 END),0) AS today,COUNT(*) AS month FROM feedback f JOIN projects p ON p.id=f.project_id WHERE p.owner_id=? AND substr(f.created_at,1,7)=?',day,owner,month);const views=await one(env,'SELECT COALESCE(SUM(CASE WHEN day=? THEN views ELSE 0 END),0) AS today,COALESCE(SUM(views),0) AS month FROM usage_daily WHERE owner_id=? AND substr(day,1,7)=?',day,owner,month);return json({websites:(await one(env,'SELECT COUNT(*) AS n FROM projects WHERE owner_id=? AND archived=0',owner)).n,members:await memberCount(env,owner),commentsToday:comments.today,commentsMonth:comments.month,viewsToday:views.today,viewsMonth:views.month,...await entitlement(env,owner)});}
 if(path==='/api/activity'&&m==='GET'){const u=await auth(req,env);return json({activity:await all(env,'SELECT a.*,p.name AS project_name FROM activity a JOIN projects p ON p.id=a.project_id WHERE (p.owner_id=? OR p.id IN (SELECT project_id FROM members WHERE user_id=?) OR p.owner_id IN (SELECT owner_id FROM workspace_members WHERE user_id=?)) AND (? IS NULL OR p.owner_id=?) ORDER BY a.created_at DESC LIMIT 100',u.id,u.id,u.id,url.searchParams.get('workspace'),url.searchParams.get('workspace'))});}
 if(path==='/api/projects'){
  const u=await auth(req,env);if(m==='GET'){return json({projects:await all(env,'SELECT p.*, (SELECT COUNT(*) FROM feedback f WHERE f.project_id=p.id AND f.status NOT IN (\'Resolved\',\'Approved\')) AS open_count,(SELECT COUNT(*) FROM feedback f WHERE f.project_id=p.id) AS feedback_count,(SELECT COUNT(*) FROM feedback f WHERE f.project_id=p.id AND f.internal=0 AND f.status NOT IN (\'Resolved\',\'Approved\')) AS public_open_count,(SELECT COUNT(*) FROM feedback f WHERE f.project_id=p.id AND f.internal=0 AND f.status=\'Reopened\') AS reopened_count,(SELECT COUNT(*) FROM approvals a WHERE a.project_id=p.id) AS approval_count,(SELECT a.id FROM attachments a JOIN feedback f ON f.id=a.feedback_id WHERE a.project_id=p.id AND a.internal=0 AND f.internal=0 AND a.name=\'screenshot.png\' ORDER BY a.created_at DESC LIMIT 1) AS cover_id FROM projects p WHERE (p.owner_id=? OR p.id IN (SELECT project_id FROM members WHERE user_id=?) OR p.owner_id IN (SELECT owner_id FROM workspace_members WHERE user_id=?)) AND (? IS NULL OR p.owner_id=?) ORDER BY created_at DESC',u.id,u.id,u.id,url.searchParams.get('workspace'),url.searchParams.get('workspace'))});}
  if(m==='POST'){const owner=b.workspaceId||u.id;if(owner!==u.id&&!await one(env,'SELECT role FROM workspace_members WHERE owner_id=? AND user_id=?',owner,u.id))fail('You cannot create reviews in this workspace.',403);const id=uid(),name=text(b.name,120);if(!name)fail('Enter a project name.');const site=validUrl(b.url);await enforceLimit(env,owner,'websites');const cap=(await entitlement(env,owner)).limits.websites;const inserted=await q(env,'INSERT INTO projects(id,owner_id,name,client,url,description,environment,created_at) SELECT ?,?,?,?,?,?,?,? WHERE ? IS NULL OR (SELECT COUNT(*) FROM projects WHERE owner_id=? AND archived=0)<?',id,owner,name,text(b.client,120),site,text(b.description),['production','staging','development'].includes(b.environment)?b.environment:'staging',now(),cap,owner,cap).run();if(!(inserted.meta?.changes??inserted.changes))fail('The website limit has been reached.',409);const l=await makeLink(env,id,{});await event(env,id,u.name,'Created the project');return json({id,clientToken:l.token},201);}
 }
 const publicMatch=path.match(/^\/api\/review\/([^/]+)$/);
 if(publicMatch){const {l,p}=await link(env,publicMatch[1]);if(m==='GET')return json({project:{id:p.id,name:p.name,url:p.url,client:p.client},branding:(await entitlement(env,p.owner_id)).plan!=='Studio',passwordRequired:!!l.password,emailRequired:!!l.require_email,permissions:{comment:!!l.can_comment,approve:!!l.can_approve}});if(m==='POST'){await rateLimit(req,env,'review');const name=text(b.name,80),email=text(b.email,254);if(!name)fail('Enter your name.');if(l.require_email&&!/^\S+@\S+\.\S+$/.test(email))fail('Enter your email address.');if(l.password&&!await passwordOK(b.password||'',l.password))fail('The link password is incorrect.',403);const token=secret();await q(env,'INSERT INTO reviewers VALUES(?,?,?,?,?)',await hash(token),l.id,name,email,now()).run();return json({token,projectId:p.id,name});}}
 const invitation=path.match(/^\/api\/invite\/([^/]+)$/);
 if(invitation){const i=await one(env,'SELECT invitations.*,projects.name FROM invitations JOIN projects ON projects.id=invitations.project_id WHERE token_hash=?',await hash(invitation[1]));if(!i||i.accepted||i.expires<Date.now())fail('This invitation is no longer available.',404);if(m==='GET')return json({name:i.name,email:i.email,role:i.role});if(m!=='POST')fail('Method not allowed.',405);const u=await auth(req,env);if(u.email!==i.email)fail('Log in with the email address this invitation was created for.',403);const project=await one(env,'SELECT owner_id FROM projects WHERE id=?',i.project_id);if(u.id===project.owner_id||await one(env,'SELECT role FROM members WHERE project_id=? AND user_id=?',i.project_id,u.id))fail('You already have access to this project.');if(!await one(env,'SELECT role FROM workspace_members WHERE owner_id=? AND user_id=?',project.owner_id,u.id))await enforceLimit(env,project.owner_id,'members');const cap=(await entitlement(env,project.owner_id)).limits.members;const accepted=await env.DB.batch([q(env,'INSERT OR REPLACE INTO members(project_id,user_id,role) SELECT project_id,?,role FROM invitations WHERE id=? AND accepted=0 AND expires>? AND (? IS NULL OR (SELECT COUNT(*) FROM (SELECT user_id FROM workspace_members WHERE owner_id=? UNION SELECT m.user_id FROM members m JOIN projects p ON p.id=m.project_id WHERE p.owner_id=? AND m.user_id<>p.owner_id))+1<? OR EXISTS(SELECT 1 FROM workspace_members WHERE owner_id=? AND user_id=?))',u.id,i.id,Date.now(),cap,project.owner_id,project.owner_id,cap,project.owner_id,u.id),q(env,'UPDATE invitations SET accepted=1 WHERE id=? AND EXISTS(SELECT 1 FROM members m WHERE m.project_id=invitations.project_id AND m.user_id=?)',i.id,u.id)]);if(!(accepted[0].meta?.changes??accepted[0].changes))fail('The invitation is unavailable or the member limit has been reached.',409);return json({id:i.project_id});}
 const pm=path.match(/^\/api\/projects\/([^/]+)(?:\/(.*))?$/);
 if(pm){const id=pm[1],sub=pm[2]||'',c=await context(req,env,id);
  if(!sub){if(m==='GET'){const p=c.project;const feedback=await all(env,'SELECT * FROM feedback WHERE project_id=?'+(c.team?'':' AND internal=0')+' ORDER BY created_at DESC',id);for(const f of feedback){f.anchor=JSON.parse(f.anchor);f.metadata=JSON.parse(f.metadata);f.comments=await all(env,'SELECT * FROM comments WHERE feedback_id=?'+(c.team?'':' AND internal=0')+' ORDER BY created_at',f.id);f.attachments=await all(env,'SELECT id,name,mime,size,comment_id FROM attachments WHERE feedback_id=?'+(c.team?'':' AND internal=0'),f.id);}return json({project:c.team?p:{id:p.id,name:p.name,url:p.url,client:p.client},feedback,team:c.team,role:c.role,name:c.name,permissions:c.team?{comment:true,approve:true}:{comment:!!c.reviewer.can_comment,approve:!!c.reviewer.can_approve},approvals:await all(env,'SELECT * FROM approvals WHERE project_id=? ORDER BY created_at DESC',id),members:c.team?await all(env,'SELECT users.id,users.name,users.email,members.role FROM members JOIN users ON users.id=members.user_id WHERE project_id=? AND users.id NOT IN (SELECT user_id FROM workspace_members WHERE owner_id=?) UNION SELECT u.id,u.name,u.email,w.role FROM workspace_members w JOIN users u ON u.id=w.user_id WHERE w.owner_id=? UNION SELECT users.id,users.name,users.email,\'owner\' FROM users WHERE id=?',id,p.owner_id,p.owner_id,p.owner_id):[]});}
   if(m==='PATCH'){admin(c);const p=c.project;if(p.archived&&b.archived===false)await enforceLimit(env,p.owner_id,'websites');const targetArchive=b.archived===undefined?p.archived:b.archived?1:0,cap=(await entitlement(env,p.owner_id)).limits.websites;const saved=await q(env,'UPDATE projects SET name=?,client=?,url=?,description=?,environment=?,archived=? WHERE id=? AND (?=1 OR archived=0 OR ? IS NULL OR (SELECT COUNT(*) FROM projects active WHERE active.owner_id=projects.owner_id AND active.archived=0)<?)',text(b.name,120)||p.name,text(b.client??p.client,120),b.url?validUrl(b.url):p.url,text(b.description??p.description),['production','staging','development'].includes(b.environment)?b.environment:p.environment,targetArchive,id,targetArchive,cap,cap).run();if(!(saved.meta?.changes??saved.changes))fail('The website limit has been reached.',409);return json({ok:true});}}
  if(sub==='links'){if(!c.team)fail('Not permitted.',403);admin(c);if(m==='GET')return json({links:await all(env,'SELECT id,label,expires,revoked,require_email,can_comment,can_approve,created_at,password IS NOT NULL AS protected FROM links WHERE project_id=? ORDER BY created_at DESC',id)});if(m==='POST'){if(b.expires&&(!Number.isFinite(new Date(b.expires).getTime())||new Date(b.expires).getTime()<Date.now()))fail('Choose a future expiry date.');return json(await makeLink(env,id,b));}}
  if(sub.startsWith('links/')&&m==='DELETE'){admin(c);await q(env,'UPDATE links SET revoked=1 WHERE id=? AND project_id=?',sub.split('/')[1],id).run();return json({ok:true});}
  if(sub==='members'&&m==='POST'){admin(c);await enforceLimit(env,c.project.owner_id,'members');const email=text(b.email,254).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))fail('Enter a valid email.');const token=secret(),role=['admin','developer','designer'].includes(b.role)?b.role:'developer';await q(env,'INSERT INTO invitations VALUES(?,?,?,?,?,?,0)',uid(),id,email,role,await hash(token),Date.now()+604800000).run();return json({token,...(b.send_email?await invitationEmail(req,env,email,token,'invite',c.project.name):{})});}
  if(sub.startsWith('members/')&&m==='DELETE'){admin(c);const userId=sub.split('/')[1];if(userId===c.project.owner_id)fail('The owner cannot be removed.');await q(env,'DELETE FROM members WHERE project_id=? AND user_id=?',id,userId).run();return json({ok:true});}
  if(sub==='capture-asset'&&m==='GET'){await rateLimit(req,env,'capture-asset',200);try{return json(await captureAsset(env,url.searchParams.get('url')));}catch(e){fail(e.status?e.message:'The image cannot be captured.',e.status||422);}}
  if(sub==='preview'&&m==='POST'){await rateLimit(req,env,'preview');const token=secret();await q(env,'DELETE FROM preview_tickets WHERE expires<?',Date.now()).run();await q(env,'INSERT INTO preview_tickets VALUES(?,?,?,?,?)',await hash(token),id,c.team?c.user.id:null,c.team?null:c.reviewer.token,Date.now()+3600000).run();return json({token});}
  if(sub==='activity'&&m==='GET')return json({activity:await all(env,'SELECT * FROM activity WHERE project_id=?'+(c.team?'':' AND internal=0')+' ORDER BY created_at DESC LIMIT 100',id)});
  if(sub==='approve'&&m==='POST'){if(!c.team&&!c.reviewer.can_approve)fail('This link does not allow approval.',403);const page=text(b.page,2048)||'/';const open=await one(env,'SELECT COUNT(*) AS count FROM feedback WHERE project_id=? AND page=? AND internal=0 AND status NOT IN (\'Resolved\',\'Approved\')',id,page);if(open.count)fail('Resolve the open feedback on this page before approving it.');await env.DB.batch([q(env,'DELETE FROM approvals WHERE project_id=? AND page=?',id,page),q(env,'INSERT INTO approvals VALUES(?,?,?,?,?)',uid(),id,page,c.name,now())]);await event(env,id,c.name,'Approved '+page);return json({ok:true});}
  if(sub==='feedback'&&m==='POST'){if(!c.team&&!c.reviewer.can_comment)fail('This link is view-only.',403);const value=text(b.text);if(!value)fail('Add a comment or a voice-note description.');if(!['desktop','tablet','phone'].includes(b.device))fail('Invalid device profile.');if(!b.anchor||!Number.isFinite(b.anchor.x)||!Number.isFinite(b.anchor.y)||b.anchor.x<0||b.anchor.x>1||b.anchor.y<0||b.anchor.y>1)fail('Invalid pin location.');const fid=uid(),n=await one(env,'SELECT COALESCE(MAX(number),0)+1 AS n FROM feedback WHERE project_id=?',id);const internal=c.team&&b.internal?1:0;await q(env,'INSERT INTO feedback VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',fid,id,n.n,c.name,value,internal,'Open',text(b.priority,20)||'Normal',text(b.assignee,80),b.device,JSON.stringify(b.anchor),text(b.page,2048)||'/',JSON.stringify(b.metadata||{}),now()).run();if(!internal)await q(env,'DELETE FROM approvals WHERE project_id=? AND page=?',id,text(b.page,2048)||'/').run();await event(env,id,c.name,'Added feedback #'+n.n,internal);await notifyMentions(req,env,c.project,c.name,value,internal,fid);return json({id:fid},201);}
  const fm=sub.match(/^feedback\/([^/]+)(?:\/(.*))?$/);
  if(fm){const f=await one(env,'SELECT * FROM feedback WHERE id=? AND project_id=?',fm[1],id);if(!f||!c.team&&f.internal)fail('Feedback not found.',404);
   if(!fm[2]&&m==='PATCH'){let status=b.status||f.status;if(!c.team&&(status==='Resolved'?!c.reviewer.can_approve:!c.reviewer.can_comment))fail('This link does not allow this action.',403);if(!['Open','In progress','In review','Resolved','Reopened','Approved'].includes(status))fail('Invalid status.');if(!c.team&&!(['Resolved','Reopened'].includes(status)&&(['In review','Resolved','Approved'].includes(f.status))))fail('Clients can approve reviewed fixes or request changes.',403);await q(env,'UPDATE feedback SET status=?,priority=?,assignee=? WHERE id=?',status,c.team?text(b.priority??f.priority,20):f.priority,c.team?text(b.assignee??f.assignee,80):f.assignee,f.id).run();if(!f.internal&&!['Resolved','Approved'].includes(status))await q(env,'DELETE FROM approvals WHERE project_id=? AND page=?',id,f.page).run();await event(env,id,c.name,'Moved #'+f.number+' to '+status,f.internal);if(c.team&&b.assignee&&b.assignee!==f.assignee)await notifyMentions(req,env,c.project,c.name,'Assigned feedback #'+f.number+' to @'+text(b.assignee,80),f.internal,f.id);return json({ok:true});}
   if(!fm[2]&&m==='DELETE'){admin(c);await env.DB.batch([q(env,'DELETE FROM comments WHERE feedback_id=?',f.id),q(env,'DELETE FROM feedback WHERE id=?',f.id)]);return json({ok:true});}
   if(fm[2]==='comments'&&m==='POST'){if(!c.team&&!c.reviewer.can_comment)fail('This link is view-only.',403);const value=text(b.text);if(!value)fail('Write a reply.');const cid=uid();await q(env,'INSERT INTO comments VALUES(?,?,?,?,?,?)',cid,f.id,c.name,value,c.team&&b.internal?1:0,now()).run();await event(env,id,c.name,'Replied to #'+f.number,c.team&&b.internal?1:0);await notifyMentions(req,env,c.project,c.name,value,f.internal||c.team&&b.internal,f.id);return json({id:cid});}
   if(fm[2]==='uploads'&&m==='POST'){if(!c.team&&!c.reviewer.can_comment)fail('This link is view-only.',403);const form=await req.formData(),file=form.get('file');const uploadLimit=Number(env.MAX_UPLOAD_BYTES)||10*1024*1024;if(!file||typeof file==='string'||file.size>uploadLimit||!file.size)fail('Upload a file no larger than '+Math.floor(uploadLimit/1024/1024)+' MB.');if(!['image/png','image/jpeg','image/webp','audio/webm','audio/ogg','audio/mp4','audio/wav','video/webm','application/pdf'].includes(file.type))fail('Supported files: PNG, JPEG, WebP, PDF and recorded audio.');let internal=f.internal;if(form.get('commentId')){const comment=await one(env,'SELECT * FROM comments WHERE id=? AND feedback_id=?',form.get('commentId'),f.id);if(!comment||!c.team&&comment.internal)fail('Reply not found.',404);internal=comment.internal;}const aid=uid();await env.MEDIA.put(aid,file.stream(),{httpMetadata:{contentType:file.type}});await q(env,'INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?,?)',aid,id,f.id,form.get('commentId')||null,text(file.name,120),file.type,file.size,internal,now()).run();return json({id:aid});}
  }
 }
 const media=path.match(/^\/api\/media\/([^/]+)$/);if(media){const a=await one(env,'SELECT * FROM attachments WHERE id=?',media[1]);if(!a)fail('File not found.',404);const c=await context(req,env,a.project_id);const f=await one(env,'SELECT internal FROM feedback WHERE id=?',a.feedback_id);if(!f||!c.team&&(a.internal||f.internal))fail('File not found.',404);const obj=await env.MEDIA.get(a.id);if(!obj)fail('File not found.',404);return new Response(obj.body,{headers:{'Content-Type':a.mime,'Content-Disposition':`inline; filename="${a.name.replace(/[^a-zA-Z0-9._-]/g,'_')}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 fail('Not found.',404);
}
async function sessionResponse(env,u,secure){const token=secret();await q(env,'INSERT INTO sessions VALUES(?,?,?)',await hash(token),u.id,Date.now()+604800000).run();return json({user:{id:u.id,name:u.name,email:u.email}},200,{'Set-Cookie':`redlyn_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${secure?'; Secure':''}`});}
export default {async fetch(req,env){try{const url=new URL(req.url);if(url.pathname.startsWith('/preview/')){try{const t=await one(env,'SELECT * FROM preview_tickets WHERE token=? AND expires>?',await hash(url.pathname.split('/')[2]),Date.now());if(!t)throw new Error('Preview session expired. Reload the review.');const p=await one(env,'SELECT * FROM projects WHERE id=?',t.project_id);if(!p)throw new Error('Review unavailable.');if(t.user_id){const permitted=p.owner_id===t.user_id||await one(env,'SELECT role FROM workspace_members WHERE owner_id=? AND user_id=?',p.owner_id,t.user_id)||await one(env,'SELECT role FROM members WHERE project_id=? AND user_id=?',p.id,t.user_id);if(!permitted)throw new Error('Review access has ended.');}else{const r=await one(env,'SELECT l.* FROM reviewers r JOIN links l ON l.id=r.link_id WHERE r.token=?',t.reviewer_token);if(!r||r.revoked||r.expires&&r.expires<Date.now()||p.archived)throw new Error('The review link is no longer available.');}const response=await previewDocument(req,env,p,t);const cap=(await entitlement(env,p.owner_id)).limits.views;const counted=await q(env,'INSERT INTO usage_daily(owner_id,day,views) VALUES(?,?,1) ON CONFLICT(owner_id,day) DO UPDATE SET views=views+1 WHERE views<?',p.owner_id,now().slice(0,10),cap).run();if(!(counted.meta?.changes??counted.changes))throw new Error('The workspace daily preview limit has been reached. Try again tomorrow.');return response;}catch(e){return previewError(e.message);}}if(url.pathname.startsWith('/api/'))return await api(req,env);if(env.ASSETS){let r=await env.ASSETS.fetch(req);if(r.status===404&&!url.pathname.includes('.'))r=await env.ASSETS.fetch(new Request(new URL('/index.html',req.url),req));const h=new Headers(r.headers);h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','strict-origin-when-cross-origin');return new Response(r.body,{status:r.status,headers:h});}return new Response('Frontend assets unavailable.',{status:503});}catch(e){if(!e.status)console.error(e);return json({error:e.status?e.message:'The service is temporarily unavailable. Please try again.'},e.status||503);}}};
