import http from 'node:http';import {DatabaseSync} from 'node:sqlite';import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import path from 'node:path';import {build} from 'esbuild';import worker from '../server/worker.mjs';
await mkdir('.data/media',{recursive:true});await mkdir('.data/build',{recursive:true});
const db=new DatabaseSync('.data/redlyn.sqlite');db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS _migrations(name TEXT PRIMARY KEY)');
for(const name of (await readdir('db/migrations')).filter(n=>n.endsWith('.sql')).sort()){if(!db.prepare('SELECT name FROM _migrations WHERE name=?').get(name)){db.exec(await readFile('db/migrations/'+name,'utf8'));db.prepare('INSERT INTO _migrations VALUES(?)').run(name);}}
const DB={prepare(sql){return {args:[],bind(...args){this.args=args;return this;},async first(){return db.prepare(sql).get(...this.args)||null;},async all(){return {results:db.prepare(sql).all(...this.args)};},async run(){return db.prepare(sql).run(...this.args);}};},async batch(statements){db.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}};
const MEDIA={async put(id,stream){await writeFile('.data/media/'+id,Buffer.from(await new Response(stream).arrayBuffer()));},async get(id){try{return {body:await readFile('.data/media/'+id)};}catch{return null;}}};
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png'};
const ASSETS={async fetch(req){const url=new URL(req.url);let p=decodeURIComponent(url.pathname);if(p==='/'||p==='/index.html')p='/index.html';if(p.includes('..'))return new Response('',{status:404});try{if(['/app.js','/bridge.js'].includes(p)){const name=p.slice(1);await build({entryPoints:['src/'+name],bundle:true,format:name==='bridge.js'?'iife':'esm',outfile:'.data/build/'+name,logLevel:'silent'});return new Response(await readFile('.data/build/'+name),{headers:{'Content-Type':'application/javascript'}});}return new Response(await readFile(path.join('public',p)),{headers:{'Content-Type':types[path.extname(p)]||'application/octet-stream'}});}catch{return new Response('',{status:404});}}};
const server=http.createServer(async(req,res)=>{try{const origin='http://'+req.headers.host;let data; if(!['GET','HEAD'].includes(req.method)){const chunks=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>12*1024*1024){res.writeHead(413);res.end('Too large');return;}chunks.push(chunk);}data=Buffer.concat(chunks);}const request=new Request(origin+req.url,{method:req.method,headers:req.headers,body:data});const response=await worker.fetch(request,{DB,MEDIA,ASSETS,...process.env});const headers=Object.fromEntries(response.headers);const cookies=response.headers.getSetCookie();if(cookies.length)headers['set-cookie']=cookies;res.writeHead(response.status,headers);res.end(Buffer.from(await response.arrayBuffer()));}catch(e){console.error(e);res.writeHead(500);res.end('Server error');}});
server.listen(3000,'127.0.0.1',()=>console.log('Redlyn is running at http://localhost:3000'));
