(() => {
 const assetCache=new Map(),pendingAssets=new Map();let nonce=null,capture=false,allowed=null,anchors=[],screenshots=true;
 const script=[...document.scripts].find(s=>s.src.includes('/bridge.js')||s.hasAttribute('data-redlyn-preview'));
 const configured=script?.dataset.reviewOrigin;const sourceURL=script?.dataset.sourceUrl;
 if(sourceURL)document.addEventListener('click',e=>{if(capture&&!e.altKey&&!altHeld)return;const a=e.target.closest('a[href]');if(!a||e.ctrlKey||e.metaKey||a.target==='_blank')return;const target=new URL(a.getAttribute('href'),sourceURL);if(target.origin===new URL(sourceURL).origin&&target.hash&&target.pathname===new URL(sourceURL).pathname){e.preventDefault();try{document.getElementById(decodeURIComponent(target.hash.slice(1)))?.scrollIntoView({behavior:'smooth'});}catch{}return;}e.preventDefault();if(target.origin===new URL(sourceURL).origin)post({type:'redlyn:navigate',url:target.href});else window.open(target.href,'_blank','noopener');},true);
 const cursor=document.createElement('div');cursor.setAttribute('data-html2canvas-ignore','true');cursor.setAttribute('data-redlyn-cursor','true');cursor.setAttribute('aria-hidden','true');cursor.textContent='+';cursor.style.cssText='position:fixed;display:none;width:32px;height:32px;border:2px solid white;border-radius:50%;background:#ea444f;color:white;font:24px/28px Arial,sans-serif;text-align:center;pointer-events:none;z-index:2147483647;transform:translate(-50%,-50%);box-shadow:0 2px 8px #0005;';document.body.append(cursor);
 const cursorStyle=document.createElement('style');cursorStyle.textContent='html[data-redlyn-comment] *,html[data-redlyn-comment]{cursor:none!important}';document.head.append(cursorStyle);
 let pointerInside=false,altHeld=false;
 const showCursor=()=>{const active=capture&&pointerInside&&!altHeld;cursor.style.display=active?'block':'none';document.documentElement.toggleAttribute('data-redlyn-comment',active);};
 document.addEventListener('pointermove',e=>{pointerInside=true;if(e.altKey)altHeld=true;cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';showCursor();},{passive:true});
 document.addEventListener('pointerleave',()=>{pointerInside=false;showCursor();});
 window.addEventListener('blur',()=>{pointerInside=false;altHeld=false;showCursor();});
 document.addEventListener('keydown',e=>{if(e.key==='Alt'){altHeld=true;showCursor();}});
 document.addEventListener('keyup',e=>{if(e.key==='Alt'){altHeld=false;showCursor();}});
 const post=(data)=>{if(nonce)parent.postMessage({...data,nonce},allowed||'*');};
 function selector(el){if(el===document.body)return 'body';if(el===document.documentElement)return 'html';if(el.id)return '#'+CSS.escape(el.id);const path=[];for(let n=el;n&&n!==document.body;n=n.parentElement){let s=n.tagName.toLowerCase();const siblings=[...(n.parentElement?.children||[])].filter(e=>e.tagName===n.tagName);if(siblings.length>1)s+=':nth-of-type('+(siblings.indexOf(n)+1)+')';path.unshift(s);if(path.length>=6)break;}return path.join(' > ');}
 const scroll=()=>{post({type:'redlyn:scroll',x:scrollX,y:scrollY,width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight});const positions=anchors.map(({id,anchor:a})=>{let x=a.x*document.documentElement.scrollWidth-scrollX,y=a.y*document.documentElement.scrollHeight-scrollY;try{const el=a.element?.selector?document.querySelector(a.element.selector):null;if(el){const r=el.getBoundingClientRect();x=r.left+r.width*(a.element.offsetX||0);y=r.top+r.height*(a.element.offsetY||0);}}catch{}return {id,x,y};});post({type:'redlyn:positions',positions});};
 window.addEventListener('message',e=>{if(e.source!==parent||parent===window)return;const m=e.data;if(m?.type==='redlyn:init'){if(configured&&e.origin!==configured)return;if(!configured&&location.pathname!=='/demo.html')return;nonce=m.nonce;screenshots=m.screenshots!==false;allowed=e.origin==='null'?'*':e.origin;post({type:'redlyn:ready',url:sourceURL||location.href});scroll();return;}if(m?.nonce!==nonce||e.origin!==allowed&&allowed!=='*')return;if(m.type==='redlyn:capture-asset-result'){pendingAssets.get(m.id)?.(m.data);pendingAssets.delete(m.id);}if(m.type==='redlyn:modifier'){altHeld=!!m.alt;showCursor();}if(m.type==='redlyn:mode'){capture=!!m.capture;showCursor();}if(m.type==='redlyn:locate'){const a=m.anchor;try{for(const tab of a.tabs||[]){const t=document.querySelector(tab.selector);if(t&&t.getAttribute('aria-selected')!=='true')t.click();}const el=a.element?.selector?document.querySelector(a.element.selector):null;if(el)el.scrollIntoView({block:'center',behavior:'smooth'});else window.scrollTo({left:a.documentX||0,top:Math.max(0,(a.documentY||0)-innerHeight/2),behavior:'smooth'});}catch{}setTimeout(scroll,400);}if(m.type==='redlyn:device')setTimeout(scroll,300);});
 window.addEventListener('message',e=>{if(e.source!==parent||e.data?.nonce!==nonce||e.data?.type!=='redlyn:anchors')return;anchors=e.data.anchors||[];scroll();});
 window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);
 async function imageData(url){if(url?.startsWith('data:image/'))return url;if(!url?.startsWith('https:'))return null;if(assetCache.has(url))return assetCache.get(url);if(assetCache.size>=10)return null;const promise=new Promise(resolve=>{const id=crypto.randomUUID();pendingAssets.set(id,resolve);post({type:'redlyn:capture-asset',id,url});setTimeout(()=>{if(pendingAssets.has(id)){pendingAssets.delete(id);resolve(null);}},9000);});assetCache.set(url,promise);return promise;}
 async function renderedScreenshot(){const clone=document.body.cloneNode(true),source=[document.body,...document.body.querySelectorAll('*')],copies=[clone,...clone.querySelectorAll('*')],jobs=[];for(let i=0;i<source.length;i++){const el=source[i],copy=copies[i];if(!copy)continue;const style=getComputedStyle(el);copy.setAttribute('style',[...style].map(k=>`${k}:${style.getPropertyValue(k)}`).filter(v=>!v.includes('url(')).join(';'));const r=el.getBoundingClientRect(),visible=r.bottom>=0&&r.top<innerHeight&&r.right>=0&&r.left<innerWidth;if(copy.tagName==='IMG'){copy.removeAttribute('src');copy.removeAttribute('srcset');if(visible)jobs.push(imageData(el.currentSrc||el.src).then(data=>{if(data)copy.src=data;}));}const bg=style.backgroundImage?.match(/^url\(["']?(.+?)["']?\)$/);if(bg&&visible)jobs.push(imageData(bg[1]).then(data=>{if(data)copy.style.backgroundImage='url("'+data+'")';}));if(copy.tagName==='CANVAS'){try{const img=document.createElement('img');img.src=el.toDataURL('image/png');img.setAttribute('style',copy.getAttribute('style'));copy.replaceWith(img);}catch{copy.remove();}}if(['SCRIPT','LINK','STYLE','IFRAME','VIDEO','AUDIO'].includes(copy.tagName)||copy.hasAttribute('data-redlyn-cursor'))copy.remove();if(el instanceof HTMLInputElement)copy.setAttribute('value',el.type==='password'?'':el.value);}await Promise.all(jobs);clone.style.margin='0';clone.style.width=document.documentElement.scrollWidth+'px';clone.style.transform=`translate(${-scrollX}px,${-scrollY}px)`;clone.style.transformOrigin='top left';const bg=getComputedStyle(document.body).backgroundColor;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${innerWidth}" height="${innerHeight}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml" style="width:${innerWidth}px;height:${innerHeight}px;overflow:hidden;background:${bg}">${new XMLSerializer().serializeToString(clone)}</div></foreignObject></svg>`;const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;});const canvas=document.createElement('canvas');canvas.width=innerWidth;canvas.height=innerHeight;canvas.getContext('2d').drawImage(img,0,0);canvas.toDataURL('image/png');return canvas;}
 document.addEventListener('click',async e=>{if(!capture||!nonce||e.altKey||altHeld||!e.isTrusted)return;e.preventDefault();e.stopImmediatePropagation();capture=false;showCursor();const el=e.target,rect=el.getBoundingClientRect(),width=document.documentElement.scrollWidth,height=document.documentElement.scrollHeight;const anchor={x:(e.clientX+scrollX)/width,y:(e.clientY+scrollY)/height,documentX:e.clientX+scrollX,documentY:e.clientY+scrollY,scrollX,scrollY,element:{selector:selector(el),tag:el.tagName.toLowerCase(),id:el.id,ariaLabel:el.getAttribute('aria-label')||'',text:(el.innerText||el.textContent||el.getAttribute('aria-label')||'').replace(/\s+/g,' ').trim().slice(0,160),offsetX:rect.width?(e.clientX-rect.left)/rect.width:0,offsetY:rect.height?(e.clientY-rect.top)/rect.height:0},tabs:[...document.querySelectorAll('[role="tab"][aria-selected="true"]')].map(el=>({selector:selector(el)}))};let screenshot=null;if(screenshots)try{const c=sourceURL?await renderedScreenshot():await (await import('html2canvas')).default(document.body,{backgroundColor:null,useCORS:true,scale:Math.min(devicePixelRatio,1.5),x:scrollX,y:scrollY,width:innerWidth,height:innerHeight,windowWidth:innerWidth,windowHeight:innerHeight,logging:false});const ctx=c.getContext('2d'),scale=c.width/innerWidth;ctx.fillStyle='#ea444f';ctx.beginPath();ctx.arc(e.clientX*scale,e.clientY*scale,14*scale,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2*scale;ctx.stroke();ctx.fillStyle='#fff';ctx.font=`${20*scale}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('+',e.clientX*scale,e.clientY*scale);screenshot=c.toDataURL('image/png');}catch{}post({type:'redlyn:pin',anchor,screenshot});},true);
})();
